### ISSUE TITLE
step file errors when trying to open in solidworks.

### ISSUE THREAD

**Issue by scubieman** [mikey63/XO-Core-XY-Printer#1]
Having issues with step file opening in solidworks. Could you reupload?

https://imgur.com/Os0eQ8v

**Comment by mikey63** [comment]
I just re-uploaded the step and also added an F3d archive.  Please try again.  Also, be sure to download the entire Zip of the repository, and then extract the file from there.  Sometimes trying to download individual files off Github doesn't work correctly
